package com.iason.trading.partner.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.*;
import lombok.extern.slf4j.Slf4j;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;
import javax.validation.constraints.Null;
import javax.websocket.server.ServerEndpoint;
import java.sql.Timestamp;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by IntelliJ IDEA
 * User: Balaji Varadharajan
 * Class/Interface/Enum Name: TradingPartner
 * Inside the package - com.iason.trading.partner.domain
 * Created Date: 4/29/2020
 * Created Time: 4:34 PM
 **/
@Entity
@Slf4j
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class TradingPartner {

    /**
     * Internal id generated by the DB. This
     * will not be exposed to outside users of the
     * APIs
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tp_sequence")
    @SequenceGenerator(name="tp_sequence", sequenceName = "tp_sequence",
            initialValue = 10001, allocationSize = 1)
    @Column(updatable = false, nullable = false)
    private Long tradingPartnerId;

    /**
     * A short description of the trading partner
     */
    @Column(name="trading_partner_desc", columnDefinition = "varchar", length = 500,
            updatable = false, nullable = false, unique = true)
    private String tradingPartnerDesc;

    /**
     * Unique Trading Partner id that is created by the user
     * This the id that is provided by the user.
     * This has to be unique
     */
    @Column(columnDefinition = "varchar",
            updatable = false, nullable = false, unique = true)
    private String tradingPartner;

    /**
     * The state that is associated with the Trading Partner
     */
    private String stateCode;

    /**
     * The HIOS ID that is associated with the Trading Partner
     */
    private String hios;

    /**
     * A trading partner can be associated to many transaction sources
     * A Transaction Source can be associated with only one trading partner
     *
     * The default fetch type for One to Many relationship is LAZY
     */
    @OneToMany(mappedBy = "tradingPartner", fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
    //@JoinColumn(name="trading_partner_sk")
    private List<TransactionSource> transactionSources = new ArrayList<>();

    @CreationTimestamp
    @Column(name="created_date", updatable = false)
    private Timestamp createdDate;

    @UpdateTimestamp
    @Column(name="last_modified_date", updatable = false)
    private Timestamp lastModifiedDate;
}
