CREATE USER IASON_TRADING_PARTNER IDENTIFIED BY IASON_TRADING_PARTNER;

GRANT CREATE SESSION TO IASON_TRADING_PARTNER;
GRANT CREATE TABLE TO IASON_TRADING_PARTNER;
GRANT CREATE SEQUENCE TO IASON_TRADING_PARTNER;
GRANT UNLIMITED TABLESPACE TO IASON_TRADING_PARTNER;